### PR TITLE
Create blank.yml

### PR DESCRIPTION
**Pull request by Biazzzzoo**

### CODE REVIEW

**Comment by havenwood** [comment]
Why add an empty `blank.yml` file? I'm curious.

**Comment by Biazzzzoo** [comment]
It's my first time. I'm still confused. I've only been studying it for a
week

**Comment by Biazzzzoo** [comment]
If it's messesing something up I'll delete it?

**Comment by havenwood** [comment]
No worries. Welcome! Pull requests here are for proposing a change to this repo. I'll close this, but please open a new pull request if you'd like to propose a change in the future.

**Comment by Biazzzzoo** [comment]
I apologize. I was just trying to connect to my square api. Took me all
day, but I got it. Week in. Api is very interesting to me

**Pull request closed without merging**
